// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: reviewprocessorpb/review_processor.proto

package reviewprocessorpb

import (
	sharedpb "github.com/bushnelljw-git/protos/go/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`       // "positive", "negative", "critical"
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"` // natural human-like response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewAnalysis) Reset() {
	*x = ReviewAnalysis{}
	mi := &file_reviewprocessorpb_review_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewAnalysis) ProtoMessage() {}

func (x *ReviewAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_reviewprocessorpb_review_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewAnalysis.ProtoReflect.Descriptor instead.
func (*ReviewAnalysis) Descriptor() ([]byte, []int) {
	return file_reviewprocessorpb_review_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewAnalysis) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ReviewAnalysis) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_reviewprocessorpb_review_processor_proto protoreflect.FileDescriptor

const file_reviewprocessorpb_review_processor_proto_rawDesc = "" +
	"\n" +
	"(reviewprocessorpb/review_processor.proto\x12\x11reviewprocessorpb\x1a\x15sharedpb/shared.proto\"B\n" +
	"\x0eReviewAnalysis\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse2W\n" +
	"\x0fReviewProcessor\x12D\n" +
	"\rAnalyzeReview\x12\x10.sharedpb.Review\x1a!.reviewprocessorpb.ReviewAnalysisBIZGgithub.com/bushnelljw-git/protos/go/reviewprocessorpb;reviewprocessorpbb\x06proto3"

var (
	file_reviewprocessorpb_review_processor_proto_rawDescOnce sync.Once
	file_reviewprocessorpb_review_processor_proto_rawDescData []byte
)

func file_reviewprocessorpb_review_processor_proto_rawDescGZIP() []byte {
	file_reviewprocessorpb_review_processor_proto_rawDescOnce.Do(func() {
		file_reviewprocessorpb_review_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviewprocessorpb_review_processor_proto_rawDesc), len(file_reviewprocessorpb_review_processor_proto_rawDesc)))
	})
	return file_reviewprocessorpb_review_processor_proto_rawDescData
}

var file_reviewprocessorpb_review_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reviewprocessorpb_review_processor_proto_goTypes = []any{
	(*ReviewAnalysis)(nil),  // 0: reviewprocessorpb.ReviewAnalysis
	(*sharedpb.Review)(nil), // 1: sharedpb.Review
}
var file_reviewprocessorpb_review_processor_proto_depIdxs = []int32{
	1, // 0: reviewprocessorpb.ReviewProcessor.AnalyzeReview:input_type -> sharedpb.Review
	0, // 1: reviewprocessorpb.ReviewProcessor.AnalyzeReview:output_type -> reviewprocessorpb.ReviewAnalysis
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reviewprocessorpb_review_processor_proto_init() }
func file_reviewprocessorpb_review_processor_proto_init() {
	if File_reviewprocessorpb_review_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviewprocessorpb_review_processor_proto_rawDesc), len(file_reviewprocessorpb_review_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reviewprocessorpb_review_processor_proto_goTypes,
		DependencyIndexes: file_reviewprocessorpb_review_processor_proto_depIdxs,
		MessageInfos:      file_reviewprocessorpb_review_processor_proto_msgTypes,
	}.Build()
	File_reviewprocessorpb_review_processor_proto = out.File
	file_reviewprocessorpb_review_processor_proto_goTypes = nil
	file_reviewprocessorpb_review_processor_proto_depIdxs = nil
}
