// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: fetcherpb/fetcher.proto

package fetcherpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewFetcher_FetchReviews_FullMethodName = "/fetcherpb.ReviewFetcher/FetchReviews"
)

// ReviewFetcherClient is the client API for ReviewFetcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewFetcherClient interface {
	FetchReviews(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
}

type reviewFetcherClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewFetcherClient(cc grpc.ClientConnInterface) ReviewFetcherClient {
	return &reviewFetcherClient{cc}
}

func (c *reviewFetcherClient) FetchReviews(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, ReviewFetcher_FetchReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewFetcherServer is the server API for ReviewFetcher service.
// All implementations must embed UnimplementedReviewFetcherServer
// for forward compatibility.
type ReviewFetcherServer interface {
	FetchReviews(context.Context, *FetchRequest) (*FetchResponse, error)
	mustEmbedUnimplementedReviewFetcherServer()
}

// UnimplementedReviewFetcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewFetcherServer struct{}

func (UnimplementedReviewFetcherServer) FetchReviews(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchReviews not implemented")
}
func (UnimplementedReviewFetcherServer) mustEmbedUnimplementedReviewFetcherServer() {}
func (UnimplementedReviewFetcherServer) testEmbeddedByValue()                       {}

// UnsafeReviewFetcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewFetcherServer will
// result in compilation errors.
type UnsafeReviewFetcherServer interface {
	mustEmbedUnimplementedReviewFetcherServer()
}

func RegisterReviewFetcherServer(s grpc.ServiceRegistrar, srv ReviewFetcherServer) {
	// If the following call pancis, it indicates UnimplementedReviewFetcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewFetcher_ServiceDesc, srv)
}

func _ReviewFetcher_FetchReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewFetcherServer).FetchReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewFetcher_FetchReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewFetcherServer).FetchReviews(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewFetcher_ServiceDesc is the grpc.ServiceDesc for ReviewFetcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewFetcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fetcherpb.ReviewFetcher",
	HandlerType: (*ReviewFetcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchReviews",
			Handler:    _ReviewFetcher_FetchReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fetcherpb/fetcher.proto",
}
